export const WEATHER_FOR_INPUT_REQUEST = "WEATHER_FOR_INPUT_REQUEST";
export const WEATHER_FOR_INPUT_REQUEST_FAILED =
  "WEATHER_FOR_INPUT_REQUEST_FAILED";
export const WEATHER_FOR_INPUT_REQUEST_SUCCESS =
  "WEATHER_FOR_INPUT_REQUEST_SUCCESS";
export const WEATHER_FOR_INPUT_REQUEST_IN_PROGRESS =
  "WEATHER_FOR_INPUT_REQUEST_IN_PROGRESS";

export const requestWeatherForInput = payload => ({
  type: WEATHER_FOR_INPUT_REQUEST,
  payload: payload
});
